config/routes.rb
Problemstosolve::Application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  

resources :users do
  resources :problems, except: [:show]
 end
 
 resources :problems, only: [:main, :show]
 
 match "/problems" => "problems#main"
  get "home/index"
  get "home/test"
  root :to => 'home#index'
  
end

# rake routes - updated - 10:47PM - 13/3/2012

# #new_user_session GET    /users/sign_in(.:format)                    devise/sessions#new
#             user_session POST   /users/sign_in(.:format)                    devise/sessions#create
#     destroy_user_session GET    /users/sign_out(.:format)                   devise/sessions#destroy
#  user_omniauth_authorize        /users/auth/:provider(.:format)             omniauth_callbacks#passthru {:provider=>/twitter|facebook|google_oauth2/}
#   user_omniauth_callback        /users/auth/:action/callback(.:format)      omniauth_callbacks#(?-mix:twitter|facebook|google_oauth2)
#            user_password POST   /users/password(.:format)                   devise/passwords#create
#        new_user_password GET    /users/password/new(.:format)               devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format)              devise/passwords#edit
#                          PUT    /users/password(.:format)                   devise/passwords#update
# cancel_user_registration GET    /users/cancel(.:format)                     devise/registrations#cancel
#        user_registration POST   /users(.:format)                            devise/registrations#create
#    new_user_registration GET    /users/sign_up(.:format)                    devise/registrations#new
#   edit_user_registration GET    /users/edit(.:format)                       devise/registrations#edit
#                          PUT    /users(.:format)                            devise/registrations#update
#                          DELETE /users(.:format)                            devise/registrations#destroy
#         new_user_problem GET    /users/:user_id/problems/new(.:format)      problems#new
#        edit_user_problem GET    /users/:user_id/problems/:id/edit(.:format) problems#edit
#             user_problem GET    /users/:user_id/problems/:id(.:format)      problems#show
#                    users GET    /users(.:format)                            users#index
#                          POST   /users(.:format)                            users#create
#                 new_user GET    /users/new(.:format)                        users#new
#                edit_user GET    /users/:id/edit(.:format)                   users#edit
#                     user GET    /users/:id(.:format)                        users#show
#                          PUT    /users/:id(.:format)                        users#update
#                          DELETE /users/:id(.:format)                        users#destroy
#                 problems        /problems(.:format)                         problems#index
#               home_index GET    /home/index(.:format)                       home#index
#                     root        /                                           home#index

app/models/problem.rb
class Problem < ActiveRecord::Base
  belongs_to :user
  attr_accessible :description, :title, :use_case, :category, :name, :twitter_username  
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,:omniauthable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :username, :name
  
  validates_presence_of :name, :username
  validates_uniqueness_of :username
  
  has_many :problems
  
  # Extending user ids to usernames
  extend FriendlyId
  friendly_id :username, use: :slugged  
  
  # methods to auth the user and push the data to db.
  
  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.username = auth.info.nickname
      user.name = auth.info.name
      user.email = auth.info.email
    end
  end
  
  # User and session validity.
  
  def self.new_with_session(params, session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"], without_protection: true) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end


  

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  # After sign in redirecting users.
  def after_sign_in_path_for(resource)
      problems_path
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @title="Home" # setting up the title haha.
  end
  def test
     @title="Uh oh!!" # setting up the title haha.
   end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # Looking where the request is coming from. And accordingly redirecting the user.
  def all
    user = User.from_omniauth(request.env["omniauth.auth"])
    #raise request.env["omniauth.auth"].to_yaml
    if user.persisted?
          flash.notice = "Signed in!"
          sign_in_and_redirect(user)
        else
          session["devise.user_attributes"] = user.attributes
          redirect_to new_user_registration_url
        end
  end
  alias_method :twitter, :all
  alias_method :facebook, :all
  alias_method :google_oauth2, :all
  
end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
  before_filter :authenticate_user!

  # No rocket science in the below methods.

  def new
    @problem = Problem.new
    @user = User.find(params[:user_id])
    @categories = ["Telecommunications","Manufacturing","Analytics and BI","Automotive","Real Estate","Healthcare","Retail and eCommerce","Enterprise & Productivity","Media / Digital","Entertainment","Travel","Education","Social","Consumer Web","Finance","Utilities"]
  end

  def edit
  end

  def index
    @user = User.find(params[:user_id])
    @problems = @user.problems
  end

  def show
    @problem = Problem.find(params[:id])
  end

  def main
    @problems = Problem.all
  end

  def create
    @user = User.find(params[:user_id])
    @problem = @user.problems.build(params[:problem])
    respond_to do |format|
      if @problem.save
        format.html { redirect_to user_problems_path(@user), notice: 'Problem was successfully created.' }
        format.json { render json: user_problems_path, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: user_problems_path.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @user = User.find(params[:user_id])
    @problem = @user.problems.find(params[:id])
  end


  def update
    @problem = Problem.find(params[:id])
    respond_to do |format|
      if @problem.update_attributes(params[:problem])
        format.html { redirect_to user_problems_path, notice: 'Problem was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @problem.errors, status: :unprocessable_entity }
      end
    end
  end



end

app/helpers/application_helper.rb
module ApplicationHelper

  def title
    base_title = "In50hrs"
    return base_title if @title.nil?
    return "#{@title} | #{base_title}"
  end

  # def flash_class(level)
  #   case level
  #   when :notice then "info"
  #   when :error then "error"
  #   when :alert then "warning"
  #   end
  # end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/problems_helper.rb
module ProblemsHelper
end

app/views/home/index.html.erb
<style>
.home-content {
	text-align: center;
}

.problem {
	color: #138caf;
	margin-top: 30px;
	font-size: 18px;
	line-height: 30px;
	text-align: center;
}
.bqstart {
	float: left;
	height: 45px;
	margin-top: -20px;
	padding-top: 45px;
	margin-bottom: -50px;
	font-size: 400%;
	color: #999999;
}

.bqend {
	float: right;
	height: 15px;
	margin-top: 0px;
	padding-top: 45px;
	font-size: 400%;
	color: #999999;
}
</style>
<% if user_signed_in? %>
	<%= render 'layouts/nav' %>
	<%end%>
	<div class="row-fluid">
		<div class="span4">
			<%= image_tag "logo.png"%>
			<h3 class="muted">Problems to solve</h3>
		</div>
		<div class="span8">
			<p class="problem"> 
				<span class="bqstart">&#8220;</span>Remember those times when a word gets stuck in your head? <br \>

				You know its cylindrical, its from a movie, it has encryption on it, and it is used for safekeeping of ancient documents - which if you try to break open will destroy the contents. Well try entering that description into google. It wont tell you the answer is a ... Cryptex. (or Caesar's box). <br \><b><u>Vijay Anand , Founder and CEO at The Startup Centre</u></b><span class="bqend">&#8221;</span>
			</p>
		</div>
	</div>
	<hr>
	<div class="home-content">
		<% if user_signed_in? %> <h3> Good you already stepped in! </h3><%else%>
		<h1><small>Looking for real world problems to solve?</small> Step right in</h1>
		<%end%>
		<% if user_signed_in? %>
		<%else%>
		<%= link_to "Create an Account", new_user_registration_path, :class => "btn btn-large btn btn-success", :type=>"button" %> 
		<%= link_to "Sign in", new_user_session_path, :class => "btn btn-large btn btn-info", :type=>"button" %> 



		<%end%>
	</div>

app/views/home/test.html.erb
<% @title = "Uh oh !! ..."%>
<%= render 'layouts/nav' %>
<%= render 'layouts/topnav' %>

<center>
<h3> We are still busy cooking the recipe. Please check back soon ;) </h3>
</center>

app/views/layouts/_footer.html.erb
<hr>
<footer>
	<p>Upcoming events: <%= link_to "Bangalore 2nd Edition, Mar 15 - 17", "http://in50hrs.com/bangalore"%> | Initiative by: <%= image_tag "tsc.png", :size=>"100x100" %> | Hosted by: <%= link_to "E2E Networks", "http://e2enetworks.com/"%> </p>
</footer>

app/views/layouts/_head.html.erb
<head>
	<title><%= title %></title>
	<%= stylesheet_link_tag  "bootstrap", "custom", "social", "http://fonts.googleapis.com/css?family=Merriweather+Sans:400,300", "http://fonts.googleapis.com/css?family=Sintony", :media => "all" %>	
	<%= csrf_meta_tags %>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<%= stylesheet_link_tag  "bootstrap-responsive.css"%>
	<script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
</head>

app/views/layouts/_nav.html.erb
<ul class="nav nav-pills pull-right">
	<li><%= link_to "Home", root_path %></li>
	<li><%= link_to "All problems", problems_path%></li>
	<% if user_signed_in? %>
	<li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
	<% if current_user.admin? %>
	<li><%= link_to "Add a new problem", new_user_problem_path(current_user)%></li>
	<li><%= link_to "Problems added by you", user_problems_path(current_user)%></li>
	<%end%>	
	<%end%>
</ul>

app/views/layouts/_topnav.html.erb
<div class="row-fluid">
	<div class="span4">
		<%= image_tag "logo.png"%>
		<h3 class="muted">Problems to solve</h3>
	</div>
	<div class="span8">
		<p class="problem"> 
			<%=@title%>
		</p>
	</div>
</div>
<hr>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<%= render 'layouts/head' %>
<body>
<div class="container-narrow">
	<% if notice %>
	<div class="alert">
	  <button type="button" class="close" data-dismiss="alert">&times;</button>
	  <%= notice %>
	</div>
	<%end%>
<%= yield %>
<%= render 'layouts/footer' %>
<%= javascript_include_tag  "jquery", "bootstrap.min" %>
</div>
</body>
</html>

app/views/problems/_form.html.erb
<% if current_user.admin? %>
	<% @title = "New Problem"%>
	<%= render 'layouts/nav' %>
	<%= render 'layouts/topnav' %>
	<!-- Start of the wrapper/content-->
	<div class="home-content">
		<div class="row">
			<div class="span6">
				<%= form_for([@user, @problem]) do |f| %>
				<%= f.label :title %>
				<%= f.text_field :title%>
				<br \>
				<%= f.label :name_of_the_person %>
				<%= f.text_field :name%>
				<br />

				<%= f.label :description %>
				<%= f.text_area :description , :rows => 15,  :class=>"input-block-level"  %>
				<br />
				<%= f.label :use_case %>
				<%= f.text_area :use_case , :rows => 10,  :class=>"input-block-level"  %>
				<br />

				<%= f.label :category %>
				<%= f.select :category, ["Telecommunications","Manufacturing","Analytics and BI","Automotive","Real Estate","Healthcare","Retail and eCommerce","Enterprise & Productivity","Media / Digital","Entertainment","Travel","Education","Social","Consumer Web","Finance","Utilities"], :prompt => 'Select One' %>
				
				<br />
				
				<%= f.label :twitter_username %>
				<div class="input-prepend">
				  <span class="add-on">@</span>
				<%= f.text_field :twitter_username, :id=>"prependedInput",:class=>"span2", :placeholder=>"Username"%>
				</div>
				<br />
				<br />
				<%= f.submit "Create post", :class => "btn" %>

				<% end %>

				<%= link_to 'Back', problems_path %>

			</div>
		</div>
	</div>
	<!-- End of the wrapper/content-->

	<%else%>
	<div class="hero-unit">
		<center><h3>Sorry honey, you have to be as cool as an admin to do that :) </h3></center>
	</div>
	<%end%>

app/views/problems/edit.html.erb
<%= render 'form' %>

app/views/problems/index.html.erb
<% @title = "Problems posted by #{@user.name}"%>
<%= render 'layouts/nav' %>
<%= render 'layouts/topnav' %>
<div class="home-content">
	<!-- Start of Dashboard body-->
	<div class="row-fluid">
		<!-- Start of previous problems section-->
		<div class="span9">
			<!-- Start of posts-->
			<% @problems.each do |p| %>
			<h3> <%= p.title %> </h3>
			<% if current_user.admin? %><h3 class="muted">(<%= link_to 'Edit', edit_user_problem_path(@user,p) %>)</h3> <%end%>
			
			<p><%= p.description %></p>
			<p><%= link_to 'Read more', problem_path(p), :class => "btn btn-success", :type => "button"%></p>
			
			<% end %>
			<!-- End of problems-->
		</div>
		<!-- End of previous posts section-->
		<!-- Start of profile photo section-->
		<div class="span3">

		</div>
		<!-- End of Dashboard body-->
</div></div>

app/views/problems/main.html.erb
<% @title = "Problems"%>
<%= render 'layouts/nav' %>
<%= render 'layouts/topnav' %>
<div class="home-content">

<!-- Running loop for each post's. But displaying one per page. -->
<% @problems.each do |p| %>
<div class="row-fluid">
	<div class="span9">
		<h2>
			
			<%=link_to "#{p.title}", problem_path(p)%>
		</h2>
		<p><%= p.description %></p>

		<div id="textbox">
			<p class="alignleft">Category: <%=p.category%></p>
			<p>
				<p class="alignright">
					<%if p.twitter_username?%>
					Submitted by <%= link_to "#{p.name}", "http://twitter.com/#{p.twitter_username}" %>  <br \>
					<%= link_to image_tag("https://api.twitter.com/1/users/profile_image/#{p.twitter_username}?size=original",:size => "70x70"), "http://twitter.com/#{p.twitter_username}"%>

					<%else%>
					Submitted by: <%= p.name%> <br \>
					<%= image_tag "pic_placeholder.jpeg" ,  :size=> "60x60"%>
					<%end%>

				</p>
			</div>
			<div style="clear: both;"></div>
		</div>
		<div class="span2 ">
			<img src= "http://placehold.it/80x80/138caf/ffffff&text=Id.<%=p.id%>" />
		</div>
	</div>

	<% end %>

	<!-- Looking for new and previous posts. -->

app/views/problems/new.html.erb
<%= render 'form' %>

app/views/problems/show.html.erb
<% @title = @problem.title%>
<%= render 'layouts/nav' %>
<%= render 'layouts/topnav' %>

<div class="home-content">
	<!-- Start of first post-->
	<div class="row-fluid">
		<ul class="breadcrumb">
		  <li> <%=link_to "Problems", home_test_path %><span class="divider"> >> </span></li>
		  <li><%=link_to "Market Research", home_test_path %> <span class="divider"> >> </span></li>
		  <li><%=link_to "Validation", home_test_path %> <span class="divider"> >> </span></li>
		 <li><%=link_to "Market Research", home_test_path %>
		</ul>

		<div class="span9">
			<p> <%= @problem.description %></p>
		</div>
		<div class="span2">
			
				<p class="alignleft">Category: <%=@problem.category%></p>
					<p class="alignright">
						<%if @problem.twitter_username?%>
						Submitted by <%= link_to "#{@problem.name}" , "http://twitter.com/#{@problem.twitter_username}" %>  <br \>
						<%= link_to image_tag("https://api.twitter.com/1/users/profile_image/#{@problem.twitter_username}?size=original",:size => "70x70"), "http://twitter.com/#{@problem.twitter_username}"%>

						<%else%>
						Submitted by: <%= @problem.name%> <br \>
						<%= image_tag "pic_placeholder.jpeg" ,  :size=> "60x60"%>
						<%end%>
			</div>

		</div>
	</div>